development: &pgsql
  adapter: postgresql
  database: {{ database.database }}
  username: {{ database.username }}
  password: {{ database.password }}
  host: {{ database.host }}
  port: {{ database.port }}
  pool: 200
  timeout: 5

production: &production
  <<: *pgsql

test:
  <<: *pgsql
