---
# Took from https://github.com/leesoh/yams/blob/master/roles/metasploit/tasks/metasploit.yml

- name: Parse Postgres URL
  local_action:
    module: command
    cmd: "python {{ role_path }}/files/pgurl2json.py"
    stdin: "{{ postgres_url }}"
  register: postgres_url_json

- name: Parse Postgres JSON data
  set_fact:
    database: "{{ postgres_url_json.stdout | from_json }}"
    cachable: no

- name: Gather package facts
  package_facts:

# This will run the next time after the first install as well, which is a bug
# as the version might no change but .version is not written during the first
# installation by msfinstall
- name: Track Metasploit version for DB migration
  become: yes
  copy:
    # Multiple package versions will break the migration tracking
    content: "{{ ansible_facts.packages['metasploit-framework'][0].version }}"
    dest: /opt/metasploit-framework/.version
  when: "'metasploit-framework' in ansible_facts.packages"
  notify:
    - migrate db
    - restart metasploit

- name: Download Metasploit installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /tmp/msfinstall
    mode: 755
  # Script adds repo and adds the metasploit-framework package
  when: "'metasploit-framework' not in ansible_facts.packages"

- name: Install Metasploit
  become: yes
  command: /tmp/msfinstall
  when: "'metasploit-framework' not in ansible_facts.packages"
  notify: migrate db
  register: msfinstall

- name: Create system Metasploit user
  become: yes
  user:
    name: metasploit
    comment: Metasploit user by Ansible
    create_home: yes

- name: Copy database config
  become: yes
  template:
    src: templates/database.yml
    dest: /opt/metasploit-framework/embedded/framework/config/database.yml
  notify: restart metasploit

- name: Create log directory
  become: yes
  file:
    path: /var/log/metasploit-web
    owner: metasploit
    mode: 1755
    state: directory

# TODO: Use SSL
- name: Install SystemD service
  become: yes
  copy:
    src: templates/metasploit-web.service
    dest: /etc/systemd/system/metasploit-web.service
  notify: restart metasploit

- name: Start Metasploit
  become: yes
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: metasploit-web

- name: Wait Metasploit
  when: msfinstall.changed
  wait_for:
    host: 127.0.0.1
    port: 5443
    state: drained
    sleep: 5
    timeout: 120
    connect_timeout: 2

- name: Create Metasploit Web user
  when: msfinstall.changed
  uri:
    url: http://127.0.0.1:5443/api/v1/users
    method: POST
    # TODO: Use vault
    body_format: json
    body: >
      {
          "username": "admin",
          "password": "admin",
          "fullname": "Ansible Admin",
          "admin": true
      }

- name: Create Metasploit Web API token
  when: msfinstall.changed
  uri:
    url: http://127.0.0.1:5443/api/v1/auth/generate-token
    method: POST
    body_format: json
    body: >
      {
          "username": "admin",
          "password": "admin"
      }
