- name: Download Vector deb
  get_url:
    url: https://packages.timber.io/vector/latest/vector-amd64.deb
    dest: /tmp/vector-amd64.deb
    mode: 755

- name: Install Vector
  become: yes
  apt:
    deb: /tmp/vector-amd64.deb
    install_recommends: yes
  notify:
    - restart vector

- name: Copy config
  become: yes
  template:
    src: templates/vector.toml
    dest: /etc/vector/vector.toml
  notify: restart vector

- name: Start Vector
  become: yes
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: vector
