---

- hosts: metasploit
  pre_tasks:
    - include_vars: ~/.tsipis/variables.yml
  roles:
    - role: vector
      vars:
        sources:
          journald.toml:
            units:
              - metasploit-web
        sinks:
          logzio.toml:
            token: "{{ logzio_token }}"
