---

- hosts: all
  include_vars: ~/.tsipis/vault.yml
  tasks:
    - name: Update Terraform output
      local_action:
        module: shell
        chdir: ../terraform
        cmd: terraform output -json
      register: terraform
    - name: Set Terraform fact
      set_fact:
        terraform: "{{ terraform.content | from_json }}"
    - name: Update & Upgrade apt
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: yes
      become: yes

- hosts: google
  become: yes
  roles:
    - role: metasploit
      vars:
        postgres_url: "{{ terraform.get('metasploit_db') }}"
    - role: concourse
      vars:
        postgres_url: "{{ terraform.get('metasploit_db') }}"
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      tags:
        - web
        - worker
    - role: faraday
      vars:
        postgres_url: "{{ terraform.get('metasploit_db') }}"
