---
- hosts: all
  tasks:
  - name: Update Terraform output
    local_action:
      module: shell
      chdir: ../terraform
      cmd: terraform output -json | jq "with_entries(.value = .value.value)" > ~/.tsipis/output.json
  - name: Update & Upgrade apt
    apt:
      autoclean: yes
      autoremove: yes
      update_cache: yes
      upgrade: yes
    become: yes
    become_method: sudo

- hosts: metasploit
  roles:
    - role: metasploit
      vars:
        postgres_url: "{{( lookup('file','~/.tsipis/output.json') | from_json).get('metasploit_db') }}"
      tags:
        - msf

