---
# Took from https://github.com/leesoh/yams/blob/master/roles/metasploit/tasks/metasploit.yml

- name: Parse Postgres URL
  local_action:
    module: command
    cmd: "python {{ role_path }}/files/pgurl2json.py"
    stdin: "{{ postgres_url }}"
  register: postgres_url_json

- name: Parse Postgres JSON data
  set_fact:
    database: "{{ postgres_url_json.stdout | from_json }}"
    cachable: no

- name: Gather package facts
  package_facts:

- name: Download Metasploit installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /tmp/msfinstall
    mode: 755
  # Script adds repo and adds the metasploit-framework package
  when: "'metasploit-framework' not in ansible_facts.packages"

- name: Install Metasploit
  become: yes
  command: /tmp/msfinstall
  when: "'metasploit-framework' not in ansible_facts.packages"

- name: Create Metasploit user
  become: yes
  user:
    name: metasploit
    comment: Metasploit user by Ansible
    create_home: true

- name: Copy database config
  become: true
  template:
    src: templates/database.yml
    dest: /opt/metasploit-framework/embedded/framework/config/database.yml

- name: Create log directory
  become: true
  file:
    path: /var/log/metasploit-web
    owner: metasploit
    mode: 700
    state: directory

- name: Install SystemD service
  become: true
  copy:
    src: templates/metasploit-web.service
    dest: /etc/systemd/system/metasploit-web.service

- name: Start Metasploit
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: metasploit-web
