- name: migrate db
  become: yes
  shell:
    chdir: /opt/metasploit-framework/embedded/framework
    cmd: bundle exec rake db:migrate
  environment:
    PATH: /opt/metasploit-framework/embedded/bin

- name: restart metasploit
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: metasploit-web
